import { execSync } from "child_process";
import fs from "fs";
import path from "path";

function getVersion(): string {
  if (process.env.VERSION && process.env.VERSION !== "0.0.0") return process.env.VERSION;

  try {
    const tag = execSync("git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n1", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    if (tag) return tag.replace(/^v/, "");
  } catch {
    // git not available or not a repo
  }

  // preserve existing non-zero version if already written (e.g. by Railway CI)
  const existing = path.resolve(__dirname, "../src/lib/version.ts");
  if (fs.existsSync(existing)) {
    const match = fs.readFileSync(existing, "utf-8").match(/APP_VERSION\s*=\s*"([^"]+)"/);
    if (match && match[1] !== "0.0.0") return match[1];
  }

  return "0.0.0";
}

const version = getVersion();
const outPath = path.resolve(__dirname, "../src/lib/version.ts");
const content = `// Auto-generated by scripts/inject-version.ts — do not edit manually.
export const APP_VERSION = "${version}";
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log(`[inject-version] Wrote version "${version}" to ${outPath}`);
