import { execSync } from "child_process";
import fs from "fs";
import path from "path";

function getVersion(): string {
  if (process.env.VERSION) return process.env.VERSION;

  try {
    const tag = execSync("git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n1", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    if (tag) return tag.replace(/^v/, "");
  } catch {
    // git not available or not a repo
  }

  return "0.0.0";
}

const version = getVersion();
const outPath = path.resolve(__dirname, "../src/lib/version.ts");
const content = `// Auto-generated by scripts/inject-version.ts — do not edit manually.
export const APP_VERSION = "${version}";
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log(`[inject-version] Wrote version "${version}" to ${outPath}`);
